export const strings = {
  siteTitle: "Belajar Hiragana & Katakana",
  siteSubtitle: "Permainan huruf Jepang untuk anak",
  homeIntro:
    "Pilih permainan di bawah. Tekan tombol speaker untuk mendengar bunyi.",
  navHome: "Beranda",
  navRead: "Baca",
  navWrite: "Tulis",
  navArrange: "Susun",
  readTitle: "Tebak & dengar",
  readHint: "Sentuh huruf, lalu dengarkan bunyi Jepang.",
  hiragana: "Hiragana",
  katakana: "Katakana",
  speak: "Dengar",
  howToReadLatin: "Cara baca (huruf Latin / romaji):",
  wordHowToRead: "Cara baca kata (romaji):",
  writeTitle: "Menggambar huruf",
  writeHint: "Pilih huruf, lalu ikuti garis tipis dengan jari atau mouse.",
  clear: "Hapus",
  arrangeTitle: "Susun kata",
  arrangeHint:
    "Susun huruf dari kiri ke kanan. Sentuh huruf di bawah untuk memasukkannya.",
  arrangeCardDesc:
    "Kata: tema, sehari-hari, plus kosakata JLPT N5–N1 (sumber terbuka, urut N5→N1). Kalimat: latihan kalimat pendek. Mode klik atau mode tulis.",
  arrangeHintWrite:
    "Mode tulis: ikuti bentuk huruf abu-abu dengan coretanmu. Tekan Selesai hanya jika sudah meniru bentuknya.",
  arrangeWriteWrong:
    "Coretan belum mengikuti bentuk huruf ini. Tekan Hapus lalu coba lagi mengikuti garis abu-abu.",
  arrangeShapeErrorTitle: "Belum pas",
  arrangeShapeErrorOk: "Oke",
  arrangeClickErrorTitle: "Belum benar",
  arrangeCatLearnWords: "Kata",
  arrangeCatLearnSentences: "Kalimat",
  arrangePickType: "Pilih jenis latihan",
  arrangePickHow: "Cara bermain",
  arrangeModeClick: "Mode klik",
  arrangeModeWrite: "Mode tulis",
  arrangeWriteProgress: "Huruf ke-{n} dari {total}",
  arrangeDoneLetter: "Selesai huruf ini",
  arrangeCheck: "Cek jawaban",
  arrangeNext: "Soal berikutnya",
  arrangeCorrect: "Hebat! Benar!",
  arrangeTryAgain: "Coba lagi, kamu pasti bisa!",
  meaning: "Arti",
  soundHint: "Petunjuk bunyi",
  footerNote:
    "Bunyi memakai suara di perangkatmu. Orang tua bisa membantu jika kurang jelas.",
} as const;
